import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import NightSky from "./components/NightSky";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div>
          <NightSky />
          <span className='shooting-star' />
          <span className='shooting-star' />
          <span className='shooting-star' />
          <span className='shooting-star' />
          <span className='shooting-star' />
          <span className='shooting-star' />
          <span className='shooting-star' />
          <span className='shooting-star' />
          <span className='shooting-star' />
          <span className='shooting-star' />
        </div>
        <Header />
        {children}
      </body>
    </html>
  );
}
